# Builds dist\TrackingGold\TrackingGold.exe
# Usage:  powershell -ExecutionPolicy Bypass -File build.ps1
#         powershell -ExecutionPolicy Bypass -File build.ps1 -Version 1.2.0 -Package   (CI: also makes dist\TrackingGold-1.2.0.zip)
param([string]$Version = "", [switch]$Package)
$ErrorActionPreference = "Stop"
Set-Location $PSScriptRoot

if ($Version) { Set-Content version.py "# Generated by build.ps1`nVERSION = `"$Version`"" -Encoding UTF8 }

if (-not (Test-Path .venv)) { python -m venv .venv }
$py = ".\.venv\Scripts\python.exe"
& $py -m pip install --upgrade pip -q
& $py -m pip install -r requirements-build.txt -q
# Optional native crypto for Telethon (faster); skip if no wheel for this Python
& $py -m pip install cryptg -q 2>$null
if ($LASTEXITCODE -ne 0) { Write-Host "cryptg not available - continuing without it" }

& $py -m PyInstaller --noconfirm --clean --onefile --console `
    --name TrackingGold --distpath dist\TrackingGold --workpath build `
    --hidden-import cryptg --hidden-import numpy --collect-all MetaTrader5 main.py
if ($LASTEXITCODE -ne 0) { throw "PyInstaller failed" }

Copy-Item .env.example dist\TrackingGold\.env.example -Force
Copy-Item install_autostart.ps1, setup_vps.ps1, update.ps1 dist\TrackingGold\ -Force
# Seed config and Telegram login on the first build only; never overwrite the ones in dist
if ((Test-Path .env) -and -not (Test-Path dist\TrackingGold\.env)) { Copy-Item .env dist\TrackingGold\.env }
if ((Test-Path tracking_session.session) -and -not (Test-Path dist\TrackingGold\tracking_session.session)) {
    Copy-Item tracking_session.session dist\TrackingGold\
}

if ($Package) {
    # Release zip: exe + scripts + config template only (no .env, session or logs)
    $name = if ($Version) { "TrackingGold-$Version" } else { "TrackingGold-dev" }
    $files = "TrackingGold.exe", ".env.example", "install_autostart.ps1", "setup_vps.ps1", "update.ps1" |
        ForEach-Object { Join-Path dist\TrackingGold $_ }
    Compress-Archive -Path $files -DestinationPath "dist\$name.zip" -Force
    Write-Host "Packaged: $PSScriptRoot\dist\$name.zip"
}

Write-Host "`nBuilt: $PSScriptRoot\dist\TrackingGold\TrackingGold.exe"
